services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\ElementDependenciesBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
